name: Build and Publish Docker Image for Exercise 03
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/build.yml"
            - ".github/workflows/build-ex03.yml"
            - "Exercise 03 Simulation/**"
jobs:
    ex03:
        uses: ./.github/workflows/build.yml
        with:
            path: "Exercise 03 Simulation"
            name: ei2-ex03
