name: Main Build Script that can be reused
on:
    workflow_call:
        inputs:
            path:
                description: Path to the folder that contains the Dockerfile
                required: true
                type: string
            name:
                description: Name of the image to be created
                required: true
                type: string
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Get current datetime
              id: datetime
              run: echo "DATETIME=$(date -u +'%Y-%m-%dT%H-%M')" >> $GITHUB_ENV
            - name: Get lowercase account name
              id: repo_owner_lowercase
              run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
            - name: Build and Push Docker image
              uses: docker/build-push-action@v5
              with:
                context: "./${{ inputs.path }}"
                push: true
                tags: |
                    ghcr.io/${{ env.REPO_OWNER }}/${{ inputs.name }}:latest
                    ghcr.io/${{ env.REPO_OWNER }}/${{ inputs.name }}:${{ env.DATETIME }}
    
