name: Build and Publish Docker Image for Exercise 06
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/build.yml"
            - ".github/workflows/build-ex06.yml"
            - "Exercise 06 SCADA/**"
jobs:
    ex03:
        uses: ./.github/workflows/build.yml
        with:
            path: "Exercise 06 SCADA"
            name: ei2-ex06
