name: Build and Publish Docker Image for Exercises 09 and 10
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/build.yml"
            - ".github/workflows/build-ex09-10.yml"
            - "Exercise 09-10 Data Analysis/**"
jobs:
    ex0910:
        uses: ./.github/workflows/build.yml
        with:
            path: "Exercise 09-10 Data Analysis"
            name: ei2-ex09-10
