name: Build and Publish Docker Image for Exercise 04
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/build.yml"
            - ".github/workflows/build-ex04.yml"
            - "Exercise 04 Dynamics and Control/**"
jobs:
    ex03:
        uses: ./.github/workflows/build.yml
        with:
            path: "Exercise 04 Dynamics and Control"
            name: ei2-ex04
