name: Build and Publish Docker Image for Exercise 11
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/build.yml"
            - ".github/workflows/build-ex11.yml"
            - "Exercise 11 Energy Data Management/**"
jobs:
    ex03:
        uses: ./.github/workflows/build.yml
        with:
            path: "Exercise 11 Energy Data Management"
            name: ei2-ex11
